export const europeanRegions = [
  'Northern Europe',
  'Eastern Europe',
  'Central Europe',
  'Southern Europe',
  'British Isles',
];
export const usRegions = [
  'US: West',
  'US: Mid-West',
  'US: South',
  'US: North-East',
];

export const regionMap: { [key: string]: string[] } = {
  'Northern Europe': ['NO', 'SE', 'FI', 'DK', 'IS', 'FO', 'AX'],
  'Eastern Europe': [
    'EE',
    'LV',
    'LT',
    'BY',
    'RU',
    'PL',
    'CZ',
    'SK',
    'HU',
    'HR',
    'SI',
    'BA',
    'ME',
    'MK',
    'AL',
    'RS',
    'BG',
    'RO',
    'MD',
    'UA',
  ],
  'Central Europe': ['DE', 'NL', 'BE', 'LU', 'AT', 'LI', 'CH', 'FR', 'MC'],
  'Southern Europe': ['PT', 'ES', 'GI', 'AD', 'VA', 'SM', 'IT', 'MT', 'GR'],
  'British Isles': ['GB', 'IM', 'IE', 'GB-ENG', 'GB-NIR', 'GB-SCT', 'GB-WLS'],
  'US: West': [
    'WA',
    'MT',
    'OR',
    'ID',
    'WY',
    'CA',
    'NV',
    'UT',
    'CO',
    'AZ',
    'NM',
    'AK',
    'HI',
  ],
  'US: Mid-West': [
    'ND',
    'SD',
    'MN',
    'WI',
    'MI',
    'NE',
    'IA',
    'IL',
    'IN',
    'OH',
    'KS',
    'MO',
  ],
  'US: South': [
    'OK',
    'AR',
    'TX',
    'LA',
    'MS',
    'AL',
    'GA',
    'FL',
    'SC',
    'TN',
    'NC',
    'KY',
    'WV',
    'VA',
    'MD',
    'DE',
    'DC',
  ],
  'US: North-East': ['PA', 'NJ', 'NY', 'CT', 'RI', 'MA', 'VT', 'NH', 'ME'],
};
